### ISSUE TITLE
Handle RPL_MOTD

### ISSUE THREAD

**Issue by Forkk** [Forkk/distirc#13]
Display MOTD messages in the network buffer.

**Comment by tilpner** [comment]
And maybe add an option for blocking them, like ZNC does. They _can_ be somewhat annyoing.

**Comment by Forkk** [comment]
I figure if they're buried away in the network buffer, it won't matter too much, but it might be nice to be able to block them I suppose.

**Comment by Forkk** [comment]
Closed by 45f6cbf00c6ed8875eba56e25fc993432d3adf8c
